#!/bin/sh

userresources=/home/v/.config/X11/Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/home/v/.config/X11//xinitrc
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xrdb -merge ~/.config/X11/Xresources
setxkbmap -option caps:escape
systemctl --user import-environment DISPLAY
clipmenud &
exec i3
